import Head from 'next/head';
import Header from '../components/Header';
import { useEffect, useState } from 'react';
import { auth } from '../firebase';
import { onAuthStateChanged } from 'firebase/auth';
import { useRouter } from 'next/router';
import Slider from '../components/Slider';
import Brands from '../components/Brands';
import MoviesCollection from '../components/MoviesCollection';
import ShowsCollection from '../components/ShowsCollection';

export default function Home({ popularMovies, popularShows, top_ratedMovies, top_ratedShows }) {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  console.log(popularMovies);

  useEffect(
    () =>
      onAuthStateChanged(auth, (user) => {
        if (user) {
          setUser({
            name: user.displayName,
            photoUrl: user.photoURL,
          });
          setLoading(false);
        } else {
          setUser(null);
          setLoading(true);
          router.push('/login');
        }
      }),
    [router]
  );

  return (
    <div>
      <Head>
        <title>
          Disney+ | The streaming home of Disney, Pixar, Marvel, Star Wars, Nat Geo and Star
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header user={user} />

      <main className="relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
        <Slider />
        <Brands />
        <MoviesCollection results={popularMovies} title="Popular Movies" />
        <ShowsCollection results={popularShows} title="Popular Shows" />

        <MoviesCollection results={top_ratedMovies} title="Top Rated Movies" />
        <ShowsCollection results={top_ratedShows} title="Top Rated Shows" />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const [popularMoviesRes, popularShowsRes, top_ratedMoviesRes, top_ratedShowsRes] =
    await Promise.all([
      fetch(
        `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
      fetch(
        `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
      fetch(
        `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
      fetch(
        `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
    ]);

  //getting json
  const [popularMovies, popularShows, top_ratedMovies, top_ratedShows] = await Promise.all([
    popularMoviesRes.json(),
    popularShowsRes.json(),
    top_ratedMoviesRes.json(),
    top_ratedShowsRes.json(),
  ]);

  // Pass data to the page via props
  return {
    props: {
      popularMovies: popularMovies.results,
      popularShows: popularShows.results,
      top_ratedMovies: top_ratedMovies.results,
      top_ratedShows: top_ratedShows.results,
    },
  };
}
